name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        env:
          YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          YC_CR_REGISTRY_ID: ${{ secrets.YC_CR_REGISTRY_ID }}
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
        script: |
          echo $YC_SA_JSON_CREDENTIALS | docker login --username oauth2accesstoken --password-stdin cr.yandex/$YC_CR_REGISTRY_ID
          docker pull cr.yandex/$YC_CR_REGISTRY_ID/app:$RELEASE_VERSION_latest
          docker stop app || true
          docker rm app || true
          docker run -d -p 3000:3000 --name app cr.yandex/$YC_CR_REGISTRY_ID/app:$RELEASE_VERSION_latest
