
name: Deploy to prod
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Yandex CR
        env:
          YC_OAUTH_TOKEN: ${{ secrets.YC_OAUTH_TOKEN }}
        run: |
          echo "${YC_OAUTH_TOKEN}" | docker login --username oauth --password-stdin cr.yandex
      - name: Check image exists
        run: docker pull cr.yandex/${{ secrets.YC_CR_REGISTRY_ID }}/app:${{ github.event.inputs.version }}_latest

      - name: SSH & deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull cr.yandex/${{ secrets.YC_CR_REGISTRY_ID }}/app:${{ github.event.inputs.version }}_latest
            docker run -d --rm --name app cr.yandex/${{ secrets.YC_CR_REGISTRY_ID }}/app:${{ github.event.inputs.version }}_latest
      - name: Add deploy comment to Issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ inputs.version }}     # номер релизной Issue, аналог версии
          body: |
            🚀 **Deployed to production**
            **Date**: $(date +'%Y-%m-%d')
            **Author**: ${{ github.actor }}
            **Docker image**: `cr.yandex/${{ secrets.YC_CR_REGISTRY_ID }}/app:${{ inputs.version }}_latest`
