name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
    - name: Get IAM Token
      env:
        YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      run: |
        IAM_TOKEN=$(curl -s -H "Metadata-Flavor: Google" -d "$YC_SA_JSON_CREDENTIALS" https://iam.api.cloud.yandex.net/iam/v1/tokens | jq -r '.iamToken')
        echo "IAM_TOKEN=$IAM_TOKEN" >> $GITHUB_ENV
    - name: Deploy to VM
      env:
        IAM_TOKEN: ${{ env.IAM_TOKEN }}
        YC_CR_REGISTRY_ID: ${{ secrets.YC_CR_REGISTRY_ID }}
        RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          echo $IAM_TOKEN | docker login --username iam --password-stdin cr.yandex/$YC_CR_REGISTRY_ID
          docker pull cr.yandex/$YC_CR_REGISTRY_ID/app:$RELEASE_VERSION_latest
          docker stop app || true
          docker rm app || true
          docker run -d -p 3000:3000 --name app cr.yandex/$YC_CR_REGISTRY_ID/app:$RELEASE_VERSION_latest
