name: PR checks  
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
