name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - run: npm ci
    - run: npm run lint
    - run: npm run test
    - name: Create release branch
      run: git checkout -b releases/${{ github.run_number }}
    - name: Build Docker image
      run: npm run build:docker
    - name: Login to Yandex Cloud Container Registry
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
    - name: Push Docker image
      env:
        CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY_ID }}
        IMAGE_NAME: app
        YC_OAUTH: ${{ secrets.YC_OAUTH }}
        RELEASE_VERSION: ${{ github.run_number }}
      run: |
          echo "$YC_OAUTH" | docker login --username oauth --password-stdin cr.yandex
          docker build -t $CR_REGISTRY/$IMAGE_NAME:$RELEASE_VERSION -t $CR_REGISTRY/$IMAGE_NAME:${RELEASE_VERSION}_latest .
          # docker push $CR_REGISTRY/$IMAGE_NAME:$RELEASE_VERSION
          # docker push $CR_REGISTRY/$IMAGE_NAME:${RELEASE_VERSION}_latest
    - name: Create Issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ github.run_number }}
      run: |
        gh issue create --title "Release $RELEASE_VERSION" --body "Release details..."
    - name: Update CHANGELOG
      env:
        RELEASE_VERSION: ${{ github.run_number }}
      run: |
        echo "## [v$RELEASE_VERSION]" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG for release $RELEASE_VERSION"
        git push origin releases/$RELEASE_VERSION
