name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - run: npm ci
    - run: npm run lint
    - run: npm run test
    - name: Create release branch
      run: git checkout -b releases/${{ github.run_number }}
    - name: Build Docker image
      env:
        CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY_ID }}
        RELEASE_VERSION: ${{ github.run_number }}
      run: docker build -t cr.yandex/${{ env.CR_REGISTRY }}/app:${{ env.RELEASE_VERSION }} -t cr.yandex/${{ env.CR_REGISTRY }}/app:${{ env.RELEASE_VERSION }}_latest .
    - name: Login to Yandex Cloud Container Registry
      env:
        YC_OAUTH_TOKEN: ${{ secrets.YC_OAUTH_TOKEN }}
        CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY_ID }}
      run: echo ${{ env.YC_OAUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex/${{ env.CR_REGISTRY }}
    - name: Push Docker image
      env:
        CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY_ID }}
        RELEASE_VERSION: ${{ github.run_number }}
      run: |
        docker push cr.yandex/${{ env.CR_REGISTRY }}/app:${RELEASE_VERSION}
        docker push cr.yandex/${{ env.CR_REGISTRY }}/app:${RELEASE_VERSION}_latest
    - name: Configure Git user
      run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
    - name: Create Git tag
      run: |
          git tag $VERSION
          git push origin $VERSION

    - name: Create GitHub Issue
      uses: peter-evans/create-issue-from-file@v5
      with:
          title: "Release $VERSION"
          content-filepath: .github/.release-issue.md
          labels: release

    - name: Update CHANGELOG.md
      run: |
          echo "## $VERSION - $(date +'%Y-%m-%d')" > .changelog.tmp
          echo "${{ steps.commits.outputs.log }}" >> .changelog.tmp
          echo "" >> .changelog.tmp
          cat CHANGELOG.md >> .changelog.tmp
          mv .changelog.tmp CHANGELOG.md

    - name: Commit CHANGELOG
      run: |
          git add CHANGELOG.md
          git commit -m "update changelog for v$VERSION"
          git push origin HEAD:releases/${{ env.VERSION }}
