name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - run: npm ci
    - run: npm run lint
    - run: npm run test
    - name: Create release branch
      run: git checkout -b releases/${{ github.run_number }}
    - name: Build Docker image
      env:
        CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY_ID }}
        RELEASE_VERSION: ${{ github.run_number }}
      run: docker build -t cr.yandex/${{ env.CR_REGISTRY }}/app:${{ env.RELEASE_VERSION }} -t cr.yandex/${{ env.CR_REGISTRY }}/app:${{ env.RELEASE_VERSION }}_latest .
    - name: Login to Yandex Cloud Container Registry
      env:
        YC_OAUTH_TOKEN: ${{ secrets.YC_OAUTH_TOKEN }}
        CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY_ID }}
      run: echo ${{ env.YC_OAUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex/${{ env.CR_REGISTRY }}
    - name: Push Docker image
      env:
        CR_REGISTRY: ${{ secrets.YC_CR_REGISTRY_ID }}
        RELEASE_VERSION: ${{ github.run_number }}
      run: |
        docker push cr.yandex/${{ env.CR_REGISTRY }}/app:${RELEASE_VERSION}
        docker push cr.yandex/${{ env.CR_REGISTRY }}/app:${RELEASE_VERSION}_latest
    - name: Update CHANGELOG
      run: |
        echo "## ${{ steps.set_version.outputs.version }} - $(date +'%Y-%m-%d')" > tmp.md
        echo "${{ steps.commits.outputs.commits }}" >> tmp.md
        tail -n +1 CHANGELOG.md >> tmp.md
        mv tmp.md CHANGELOG.md
        git commit -am "chore: update CHANGELOG for release ${{ steps.set_version.outputs.version }}"
        git push origin HEAD:main
    - name: Create Issue with release info
      uses: peter-evans/create-issue-from-file@v4
      with:
          title: "Release ${{ steps.set_version.outputs.version }}"
          content: |
            **Date**: $(date)
            **Author**: ${{ github.actor }}
            **Version**: ${{ steps.set_version.outputs.version }}
            **Commits**:
            ```
            ${{ steps.commits.outputs.commits }}
            ```
            **Docker**: cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ steps.set_version.outputs.version }}
